# Automatic pipeline to show diff for dev, test, or prod

name: Show AWS CDK diff (dev/staging/prod)

on:
  pull_request:
    branches:
      - dev
      - test
      - main

jobs:
  show_diff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install npm and AWS CDK
        run: |
          sudo apt update -y
          sudo apt install nodejs npm -y
          npm install
          npm install -g aws-cdk
          npm install aws-cdk-lib

      - name: CDK diff for each environment
        run: |
          if [ "${{ github.base_ref }}" == "dev" ]; then
            cdk diff --exclusively "dev*" --strict --no-change-set;
          elif [ "${{ github.base_ref }}" == "staging" ]; then
            cdk diff --exclusively "staging*" --strict --no-change-set;
          elif [ "${{ github.base_ref }}" == "main" ]; then
            cdk diff --exclusively "prod*" --strict --no-change-set;
          fi
        env:
          NODE_ENV: ${{ github.base_ref }}
